/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RewardSystemInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "earnPoints" | "grantPoints" | "isMember" | "join" | "members" | "redeem" | "rewardCost" | "transferPoints"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MemberJoined" | "PointsEarned" | "PointsGranted" | "PointsTransferred" | "RewardRedeemed"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'earnPoints', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantPoints', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isMember', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'join', values?: undefined): string;
encodeFunctionData(functionFragment: 'members', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rewardCost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferPoints', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earnPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantPoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'join', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'members', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferPoints', data: BytesLike): Result;
  }

  
    export namespace MemberJoinedEvent {
      export type InputTuple = [member: AddressLike];
      export type OutputTuple = [member: string];
      export interface OutputObject {member: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PointsEarnedEvent {
      export type InputTuple = [member: AddressLike, points: BigNumberish];
      export type OutputTuple = [member: string, points: bigint];
      export interface OutputObject {member: string, points: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PointsGrantedEvent {
      export type InputTuple = [admin: AddressLike, member: AddressLike, amount: BigNumberish];
      export type OutputTuple = [admin: string, member: string, amount: bigint];
      export interface OutputObject {admin: string, member: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PointsTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, to: string, amount: bigint];
      export interface OutputObject {from: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardRedeemedEvent {
      export type InputTuple = [member: AddressLike, reward: BigNumberish, cost: BigNumberish];
      export type OutputTuple = [member: string, reward: bigint, cost: bigint];
      export interface OutputObject {member: string, reward: bigint, cost: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RewardSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): RewardSystem;
    waitForDeployment(): Promise<this>;

    interface: RewardSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    earnPoints: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    grantPoints: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isMember: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    join: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    members: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, boolean] & {points: bigint, exists: boolean }],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [reward: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rewardCost: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    transferPoints: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'earnPoints'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantPoints'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isMember'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'join'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'members'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, boolean] & {points: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [reward: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardCost'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferPoints'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MemberJoined'): TypedContractEvent<MemberJoinedEvent.InputTuple, MemberJoinedEvent.OutputTuple, MemberJoinedEvent.OutputObject>;
getEvent(key: 'PointsEarned'): TypedContractEvent<PointsEarnedEvent.InputTuple, PointsEarnedEvent.OutputTuple, PointsEarnedEvent.OutputObject>;
getEvent(key: 'PointsGranted'): TypedContractEvent<PointsGrantedEvent.InputTuple, PointsGrantedEvent.OutputTuple, PointsGrantedEvent.OutputObject>;
getEvent(key: 'PointsTransferred'): TypedContractEvent<PointsTransferredEvent.InputTuple, PointsTransferredEvent.OutputTuple, PointsTransferredEvent.OutputObject>;
getEvent(key: 'RewardRedeemed'): TypedContractEvent<RewardRedeemedEvent.InputTuple, RewardRedeemedEvent.OutputTuple, RewardRedeemedEvent.OutputObject>;

    filters: {
      
      'MemberJoined(address)': TypedContractEvent<MemberJoinedEvent.InputTuple, MemberJoinedEvent.OutputTuple, MemberJoinedEvent.OutputObject>;
      MemberJoined: TypedContractEvent<MemberJoinedEvent.InputTuple, MemberJoinedEvent.OutputTuple, MemberJoinedEvent.OutputObject>;
    

      'PointsEarned(address,uint256)': TypedContractEvent<PointsEarnedEvent.InputTuple, PointsEarnedEvent.OutputTuple, PointsEarnedEvent.OutputObject>;
      PointsEarned: TypedContractEvent<PointsEarnedEvent.InputTuple, PointsEarnedEvent.OutputTuple, PointsEarnedEvent.OutputObject>;
    

      'PointsGranted(address,address,uint256)': TypedContractEvent<PointsGrantedEvent.InputTuple, PointsGrantedEvent.OutputTuple, PointsGrantedEvent.OutputObject>;
      PointsGranted: TypedContractEvent<PointsGrantedEvent.InputTuple, PointsGrantedEvent.OutputTuple, PointsGrantedEvent.OutputObject>;
    

      'PointsTransferred(address,address,uint256)': TypedContractEvent<PointsTransferredEvent.InputTuple, PointsTransferredEvent.OutputTuple, PointsTransferredEvent.OutputObject>;
      PointsTransferred: TypedContractEvent<PointsTransferredEvent.InputTuple, PointsTransferredEvent.OutputTuple, PointsTransferredEvent.OutputObject>;
    

      'RewardRedeemed(address,uint8,uint256)': TypedContractEvent<RewardRedeemedEvent.InputTuple, RewardRedeemedEvent.OutputTuple, RewardRedeemedEvent.OutputObject>;
      RewardRedeemed: TypedContractEvent<RewardRedeemedEvent.InputTuple, RewardRedeemedEvent.OutputTuple, RewardRedeemedEvent.OutputObject>;
    
    };
  }