/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AccessControl', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AccessControl__factory>
getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'CustomErrors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CustomErrors__factory>
getContractFactory(name: 'HelloWorld', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HelloWorld__factory>
getContractFactory(name: 'RewardSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardSystem__factory>
getContractFactory(name: 'Wallet', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Wallet__factory>

  getContractAt(name: 'AccessControl', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AccessControl>
getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'CustomErrors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CustomErrors>
getContractAt(name: 'HelloWorld', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HelloWorld>
getContractAt(name: 'RewardSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardSystem>
getContractAt(name: 'Wallet', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Wallet>

  deployContract(name: 'AccessControl', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessControl>
deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'CustomErrors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CustomErrors>
deployContract(name: 'HelloWorld', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HelloWorld>
deployContract(name: 'RewardSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardSystem>
deployContract(name: 'Wallet', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Wallet>

  deployContract(name: 'AccessControl', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessControl>
deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'CustomErrors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CustomErrors>
deployContract(name: 'HelloWorld', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HelloWorld>
deployContract(name: 'RewardSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardSystem>
deployContract(name: 'Wallet', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Wallet>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  