/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { CustomErrors, CustomErrorsInterface } from "../../CustomErrors.sol/CustomErrors.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "sent",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "required",
        "type": "uint256"
      }
    ],
    "name": "TooLow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "number",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "setNumber",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b50335f5f6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506103298061005b5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c80633fb5c1cb146100435780638381f58a1461005f5780638da5cb5b1461007d575b5f5ffd5b61005d600480360381019061005891906101df565b61009b565b005b61006761017e565b6040516100749190610219565b60405180910390f35b610085610184565b6040516100929190610271565b60405180910390f35b5f5f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161461012b57336040517f245aecd30000000000000000000000000000000000000000000000000000000081526004016101229190610271565b60405180910390fd5b600a8110156101745780600a6040517f7e4b459300000000000000000000000000000000000000000000000000000000815260040161016b9291906102cc565b60405180910390fd5b8060018190555050565b60015481565b5f5f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f5ffd5b5f819050919050565b6101be816101ac565b81146101c8575f5ffd5b50565b5f813590506101d9816101b5565b92915050565b5f602082840312156101f4576101f36101a8565b5b5f610201848285016101cb565b91505092915050565b610213816101ac565b82525050565b5f60208201905061022c5f83018461020a565b92915050565b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f61025b82610232565b9050919050565b61026b81610251565b82525050565b5f6020820190506102845f830184610262565b92915050565b5f819050919050565b5f819050919050565b5f6102b66102b16102ac8461028a565b610293565b6101ac565b9050919050565b6102c68161029c565b82525050565b5f6040820190506102df5f83018561020a565b6102ec60208301846102bd565b939250505056fea26469706673582212202b493b3c0c1e2d25ca0f4a4ff9d3a63fe9fc5a2f1f62c88da8be5fb1db207ba764736f6c634300081f0033";

  
      type CustomErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CustomErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CustomErrors__factory extends ContractFactory {
    
      constructor(...args: CustomErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CustomErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CustomErrors__factory {
      return super.connect(runner) as CustomErrors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CustomErrorsInterface {
      return new Interface(_abi) as CustomErrorsInterface;
    }
    
    override attach(address: string | Addressable): CustomErrors {
      return super.attach(address) as CustomErrors;
    }
  static connect(address: string, runner?: ContractRunner | null): CustomErrors {
      return new Contract(address, _abi, runner) as unknown as CustomErrors;
    }
  }

  
  