/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AccessControlInterface extends Interface {
    getFunction(nameOrSignature: "admins" | "assignAdminRole" | "assignOtherRole" | "members" | "supporters"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RoleAssigned"): EventFragment;

    encodeFunctionData(functionFragment: 'admins', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'assignAdminRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'assignOtherRole', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'members', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supporters', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'admins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignAdminRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assignOtherRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'members', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supporters', data: BytesLike): Result;
  }

  
    export namespace RoleAssignedEvent {
      export type InputTuple = [account: AddressLike, role: string];
      export type OutputTuple = [account: string, role: string];
      export interface OutputObject {account: string, role: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AccessControl extends BaseContract {
    
    connect(runner?: ContractRunner | null): AccessControl;
    waitForDeployment(): Promise<this>;

    interface: AccessControlInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admins: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    assignAdminRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    assignOtherRole: TypedContractMethod<
      [account: AddressLike, role: string, ],
      [void],
      'nonpayable'
    >
    

    
    members: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    supporters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admins'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'assignAdminRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assignOtherRole'): TypedContractMethod<
      [account: AddressLike, role: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'members'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supporters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'RoleAssigned'): TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;

    filters: {
      
      'RoleAssigned(address,string)': TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;
      RoleAssigned: TypedContractEvent<RoleAssignedEvent.InputTuple, RoleAssignedEvent.OutputTuple, RoleAssignedEvent.OutputObject>;
    
    };
  }