/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface WalletInterface extends Interface {
    getFunction(nameOrSignature: "contractBalance" | "deposit" | "withdrawal"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositMade" | "FallbackCalled" | "WithdrawalMade"): EventFragment;

    encodeFunctionData(functionFragment: 'contractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawal', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'contractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawal', data: BytesLike): Result;
  }

  
    export namespace DepositMadeEvent {
      export type InputTuple = [accountAddress: AddressLike, amount: BigNumberish];
      export type OutputTuple = [accountAddress: string, amount: bigint];
      export interface OutputObject {accountAddress: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FallbackCalledEvent {
      export type InputTuple = [accountAddress: AddressLike];
      export type OutputTuple = [accountAddress: string];
      export interface OutputObject {accountAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalMadeEvent {
      export type InputTuple = [accountAddress: AddressLike, amount: BigNumberish];
      export type OutputTuple = [accountAddress: string, amount: bigint];
      export interface OutputObject {accountAddress: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Wallet extends BaseContract {
    
    connect(runner?: ContractRunner | null): Wallet;
    waitForDeployment(): Promise<this>;

    interface: WalletInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    contractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    withdrawal: TypedContractMethod<
      [withdrawalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'contractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdrawal'): TypedContractMethod<
      [withdrawalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositMade'): TypedContractEvent<DepositMadeEvent.InputTuple, DepositMadeEvent.OutputTuple, DepositMadeEvent.OutputObject>;
getEvent(key: 'FallbackCalled'): TypedContractEvent<FallbackCalledEvent.InputTuple, FallbackCalledEvent.OutputTuple, FallbackCalledEvent.OutputObject>;
getEvent(key: 'WithdrawalMade'): TypedContractEvent<WithdrawalMadeEvent.InputTuple, WithdrawalMadeEvent.OutputTuple, WithdrawalMadeEvent.OutputObject>;

    filters: {
      
      'DepositMade(address,uint256)': TypedContractEvent<DepositMadeEvent.InputTuple, DepositMadeEvent.OutputTuple, DepositMadeEvent.OutputObject>;
      DepositMade: TypedContractEvent<DepositMadeEvent.InputTuple, DepositMadeEvent.OutputTuple, DepositMadeEvent.OutputObject>;
    

      'FallbackCalled(address)': TypedContractEvent<FallbackCalledEvent.InputTuple, FallbackCalledEvent.OutputTuple, FallbackCalledEvent.OutputObject>;
      FallbackCalled: TypedContractEvent<FallbackCalledEvent.InputTuple, FallbackCalledEvent.OutputTuple, FallbackCalledEvent.OutputObject>;
    

      'WithdrawalMade(address,uint256)': TypedContractEvent<WithdrawalMadeEvent.InputTuple, WithdrawalMadeEvent.OutputTuple, WithdrawalMadeEvent.OutputObject>;
      WithdrawalMade: TypedContractEvent<WithdrawalMadeEvent.InputTuple, WithdrawalMadeEvent.OutputTuple, WithdrawalMadeEvent.OutputObject>;
    
    };
  }